worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream auth_service {
        server auth-service:3001;
    }

    upstream account_service {
        server account-service:3002;
    }

    server {
        listen 80;

        location /api/auth {
            proxy_pass http://auth_service;
        }

        location /api/accounts {
            proxy_pass http://account_service;
        }
    }
}
